### ISSUE TITLE
UX - autocompletion - data entry / entry selection issues

### ISSUE THREAD

**Issue by CristianoFugazza** [SP7-Ritmare/EDI-NG_client#21]
Tested on field "Parametro osservativo" in RNDT.
When filling in autocompletion fields:
- queries start after the first character is specified (not after three, which was the behavior in the previous EDI), slowing down the interface
- focus is lost (the cursor disappearing) when the list of suggestions appears (or when the related query returns the result, it is not possible to tell which is the action triggering the issue) and no further character can be entered until focus is restored by clicking with the mouse on the field
- clicking on an entry in the list does not select it

**Comment by fabiopavesi** [comment]
Fixed with (https://github.com/SP7-Ritmare/EDI-NG_client/commit/3c9477eeeadfdfcfdd4c376e8a30c5c8bc39f884)
