### ISSUE TITLE
UX - drop-down lists - interaction issues

### ISSUE THREAD

**Issue by CristianoFugazza** [SP7-Ritmare/EDI-NG_client#22]
- the user is prone to click on the arrow at the right-end side of the field in order to show the list of options but has to move the mouse back to the left-end side in order to choose an option
- after scrolling to the end (start) of the list, it is the underlying page to move down (up)
- the user should be able to deselect the field (also for mandatory ones, just in case he wants to fill it in later)

**Comment by ptagliolato** [comment]
I deleted the item, because it is duplicated in issue "Graphic design of interface#24"
- mandatory fields are initialized with an asterisk "*" (also those at the end of field names are redundant if color is chosen as the way to distinguish between mandatory and optional fields)
