### ISSUE TITLE
UX - autocompletion - items of type "select" / multiple elements

### ISSUE THREAD

**Issue by CristianoFugazza** [SP7-Ritmare/EDI-NG_client#23]
Tested with element "Responsabile dei metadati" in RNDT
- when deleting the value of an item that has been selected via autocompletion, the items in the same element that where filled in on the basis of the first (because of type "select") are not deleted
- when duplicating the element, the items of type "select" of the previous one are duplicated
- after entering the first character in the autocompletion field, the list of suggestions is opened both for the current field and for the previous one 
- the latter list of suggestions can not be closed if not by selecting a value, but then autocompletion for this field stops working

**Comment by fabiopavesi** [comment]
Fixed in https://github.com/SP7-Ritmare/EDI-NG_client/commit/03f65c3778cc3e0572763cccedb0032cb27f2e5e
