### ISSUE TITLE
verify for sml:history/sml:EventList/sml:event gml:id element duplication

### ISSUE THREAD

**Issue by oggioniale** [SP7-Ritmare/EDI-NG_client#40]
<sml:history>
                <sml:EventList>
                    <sml:event>
                        <sml:Event>
                            <swe:label>installazione</swe:label>
                            <swe:description>descrizione</swe:description>
                            <sml:time>
                                <gml:TimeInstant gml:id="event_20180201T05:00:00+04:30Z">
                                    <gml:timePosition>2018-02-01T05:00:00+04:30Z</gml:timePosition>
                                </gml:TimeInstant>
                            </sml:time>
                        </sml:Event>
                    </sml:event>
                    <sml:event>
                        <sml:Event>
                            <swe:label>calibrazione</swe:label>
                            <swe:description>descrizione</swe:description>
                            <sml:time>
                                <gml:TimeInstant>
                                    <gml:timePosition>2018-02-02T00:00:00-03:00Z</gml:timePosition>
                                </gml:TimeInstant>
                            </sml:time>
                        </sml:Event>
                    </sml:event>
                </sml:EventList>
            </sml:history>

**Comment by CristianoFugazza** [comment]
???

2018-02-28 12:10 GMT+01:00 Alessandro Oggioni <notifications@github.com>:

**Comment by fabiopavesi** [comment]
Function datatype fields used to get lost upon duplication of element: I fixed it
